### ISSUE TITLE
uninitialized constant Origami::Graphics::Color::SPACE (NameError)

### ISSUE THREAD

**Issue by JasonBarnabe** [gdelugre/origami#19]
When running [this code](https://github.com/gdelugre/origami/blob/8ba8d707c6d2d63041a1fe323facb7925e3823e2/examples/forms/javascript.rb#L33-L35) I get:

```
/Users/jason/.rvm/gems/ruby-2.3.3/gems/origami-2.0.2/lib/origami/graphics/colors.rb:206:in `block in <class:Instruction>': uninitialized constant Origami::Graphics::Color::SPACE (NameError)
	from /Users/jason/.rvm/gems/ruby-2.3.3/gems/origami-2.0.2/lib/origami/graphics/instruction.rb:48:in `render'
	from /Users/jason/.rvm/gems/ruby-2.3.3/gems/origami-2.0.2/lib/origami/graphics/xobject.rb:378:in `set_stroke_color'
	from /Users/jason/.rvm/gems/ruby-2.3.3/gems/origami-2.0.2/lib/origami/graphics/xobject.rb:165:in `draw_rectangle'
```

**Comment by gdelugre** [comment]
Thank you, fixed in release ``2.0.3``.
